Update patch set 1
Patch Set 1: Code-Review-1

It is not working, Sam with error like:
"AttributeError: type object 'RecordsetsTest' has no attribute 'test_create_and_delete_records_on_existing_zone_00003_A'"

I could make an easier change to the designate-tempest code to fix this.

Patch-set: 1
Reviewer: Gerrit User 1000190 <1000190@f182a8af-62ca-4ceb-ab81-14f8fec9c6c5>
Label: Code-Review=-1