Add puppet-kmod CI
Use dummy job because puppet-kmod currently doesn't pass rake lint on
Focal due to the following errors

 ubuntu@jake-focal:~/puppet-kmod$ bundle exec ./lint.py rake lint
 rake aborted!
 SyntaxError: /home/ubuntu/puppet-kmod/.bundled_gems/gems/console-1.16.2/lib/console/progress.rb:77: syntax error, unexpected ')'
                         @output.info(@subject, ...)

Change-Id: I8cdc3ecd76557432b179ca12eb8cfa4ecd12f3df